services:
  db:
    image: postgres:16
    container_name: ems-postgres
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_pass
#    command: ["postgres", "-c", "TimeZone=UTC"]
    ports:
      - "5432:5432"
    volumes:
      - ems_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ems-redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: ems_backend
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  ems_pgdata:
